CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "mobile" varchar(15),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "user_roles" (
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_addresses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "full_name" varchar(100),
  "address_line1" text,
  "address_line2" text,
  "city" varchar(50),
  "state" varchar(50),
  "postal_code" varchar(20),
  "country" varchar(50),
  "phone_number" varchar(20),
  "is_default" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "password_reset_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "email_verification_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "token" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "verified" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "otp_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "otp_code" varchar(10),
  "type" varchar(50),
  "sent_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "is_verified" boolean DEFAULT false
);

CREATE TABLE "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "is_superadmin" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "admin_roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "admin_activity_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" integer NOT NULL,
  "action" text,
  "timestamp" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_type" varchar(50),
  "actor_id" integer,
  "action" text,
  "target_table" varchar(100),
  "target_id" integer,
  "timestamp" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "seller_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "shop_name" varchar(150),
  "description" text,
  "is_verified" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "seller_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" integer NOT NULL,
  "doc_type" varchar(100),
  "doc_url" text,
  "status" enum(pending,approved,rejected) DEFAULT 'pending',
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_id" integer,
  "reported_user_id" integer,
  "reason" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "status" enum(pending,reviewed,dismissed) DEFAULT 'pending'
);

CREATE TABLE "dashboard_widgets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" integer,
  "widget_name" varchar(100),
  "is_enabled" boolean DEFAULT true,
  "display_order" integer
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "email" varchar(150),
  "mobile" varchar(15),
  "total_amount" decimal(10,2),
  "status" enum(pending,confirmed,shipped,delivered,cancelled) DEFAULT 'pending',
  "payment_status" enum(pending,paid,failed) DEFAULT 'pending',
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "price" decimal(10,2)
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int,
  "product_id" int,
  "quantity" int DEFAULT 1
);

CREATE TABLE "shipping_methods" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "cost" decimal(10,2),
  "estimated_days" int
);

CREATE TABLE "shipping_addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "full_name" varchar(100),
  "address_line1" text,
  "address_line2" text,
  "city" varchar(50),
  "state" varchar(50),
  "postal_code" varchar(20),
  "country" varchar(50),
  "phone_number" varchar(20)
);

CREATE TABLE "billing_addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "full_name" varchar(100),
  "address_line1" text,
  "address_line2" text,
  "city" varchar(50),
  "state" varchar(50),
  "postal_code" varchar(20),
  "country" varchar(50),
  "phone_number" varchar(20)
);

CREATE TABLE "order_status_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "old_status" varchar(50),
  "new_status" varchar(50),
  "changed_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "delivery_tracking_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "tracking_number" varchar(100),
  "carrier" varchar(100),
  "status" varchar(100),
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "invoice_documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "invoice_url" text,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "order_cancellations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "reason" text,
  "requested_by" varchar(100),
  "status" enum(requested,approved,rejected) DEFAULT 'requested',
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "user_id" int,
  "amount" decimal(10,2),
  "status" enum(pending,successful,failed) DEFAULT 'pending',
  "payment_method_id" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "payment_methods" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "payment_attempts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" int,
  "attempt_time" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "response_code" varchar(100),
  "response_message" text,
  "success" boolean
);

CREATE TABLE "payment_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" int,
  "log" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "refunds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" int,
  "refund_amount" decimal(10,2),
  "reason" text,
  "refund_status" enum(initiated,processed,failed) DEFAULT 'initiated',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "tax_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" int,
  "tax_percentage" decimal(5,2),
  "tax_amount" decimal(10,2),
  "jurisdiction" varchar(100)
);

CREATE TABLE "bank_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "account_holder_name" varchar(100),
  "bank_name" varchar(100),
  "account_number" varchar(50),
  "ifsc_code" varchar(20),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "payouts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "amount" decimal(10,2),
  "payout_status" enum(scheduled,processing,completed,failed) DEFAULT 'scheduled',
  "scheduled_at" timestamp,
  "processed_at" timestamp
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "parent_id" int DEFAULT null
);

CREATE TABLE "brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "description" text,
  "price" decimal(10,2) NOT NULL,
  "category_id" int,
  "brand_id" int,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "image_url" text NOT NULL,
  "is_primary" boolean DEFAULT false
);

CREATE TABLE "product_variants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "variant_name" varchar(100),
  "variant_value" varchar(100),
  "price_modifier" decimal(10,2) DEFAULT 0,
  "stock" int DEFAULT 0
);

CREATE TABLE "product_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "product_tag_map" (
  "product_id" int,
  "tag_id" int,
  "primary" key(product_id,tag_id)
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "total_stock" int DEFAULT 0,
  "reserved_stock" int DEFAULT 0
);

CREATE TABLE "inventory_reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "quantity" int,
  "reserved_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "expires_at" datetime
);

CREATE TABLE "inventory_adjustments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "quantity_change" int,
  "reason" varchar(255),
  "adjusted_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "product_audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "action" varchar(50),
  "changed_by" int,
  "change_summary" text,
  "timestamp" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "bundle_products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bundle_name" varchar(150),
  "description" text,
  "price" decimal(10,2),
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "bundle_items" (
  "bundle_id" int,
  "product_id" int,
  "quantity" int DEFAULT 1,
  "primary" key(bundle_id,product_id)
);

CREATE TABLE "product_availability" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "location" varchar(100),
  "stock" int,
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "event_logs" (
  "id" serial PRIMARY KEY,
  "service_name" varchar(100),
  "event_type" varchar(100),
  "payload" jsonb,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "retry_queue" (
  "id" serial PRIMARY KEY,
  "service_name" varchar(100),
  "operation" varchar(100),
  "payload" jsonb,
  "retry_count" int DEFAULT 0,
  "status" enum(pending,in_progress,failed,completed) DEFAULT 'pending',
  "next_retry_at" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "service_health" (
  "id" serial PRIMARY KEY,
  "service_name" varchar(100) UNIQUE,
  "status" enum(healthy,degraded,down) DEFAULT 'healthy',
  "last_heartbeat" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "api_usage_stats" (
  "id" serial PRIMARY KEY,
  "service_name" varchar(100),
  "endpoint" varchar(255),
  "method" varchar(10),
  "user_id" int,
  "status_code" int,
  "timestamp" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "dead_letter_queue" (
  "id" serial PRIMARY KEY,
  "service_name" varchar(100),
  "failed_payload" jsonb,
  "reason" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON TABLE "user_roles" IS 'Mapping of users to roles (Many-to-Many)';

COMMENT ON COLUMN "orders"."user_id" IS 'ON DELETE SET NULL';

COMMENT ON COLUMN "order_items"."product_id" IS 'ON DELETE SET NULL';

COMMENT ON COLUMN "cart_items"."product_id" IS 'ON DELETE SET NULL';

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_reset_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "email_verification_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "otp_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "admin_activity_logs" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("id");

ALTER TABLE "seller_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "seller_documents" ADD FOREIGN KEY ("seller_id") REFERENCES "seller_profiles" ("id");

ALTER TABLE "dashboard_widgets" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "shipping_addresses" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "billing_addresses" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "delivery_tracking_logs" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "invoice_documents" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_cancellations" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "payment_attempts" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "payment_logs" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "refunds" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "tax_details" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_tag_map" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_tag_map" ADD FOREIGN KEY ("tag_id") REFERENCES "product_tags" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "inventory_reservations" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "inventory_adjustments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "bundle_items" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundle_products" ("id");

ALTER TABLE "bundle_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_availability" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "dashboard_widgets" ADD FOREIGN KEY ("admin_id") REFERENCES "dashboard_widgets" ("is_enabled");
